import type { NextPage } from "next"
import Head from "next/head"
import { trpc } from "utils/trpc"

const Home: NextPage = () => {
  const { data, isLoading } = trpc.useQuery(["hello", { text: "toyosi" }])

  if (isLoading) return <div>Loading......</div>

  if (data) return <div>{data.greeting}</div>

  return (
    <div className="max-w-2xl mx-auto">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1 className="text-red-500 text-center">Hello</h1>
    </div>
  )
}

export default Home
